# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dd56d01806d20916e37aa2cdae9b4db9c2a456eb880f4e1e11bd3b6b4055a82baaea9788d7f28544c1aab814ed3480f1201519fcc95cc9658330537063aaaad

test:
  secret_key_base: 7f1fe863efa60d777eeadad8c73fb01598094cef9da7baee7e8b5345ce6d3ada1c0bc9d6c4487a217f8c83f3a69e365589ffe1e7fdcca04a65ee723fb0dc0e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
